version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Map to the provided port (default in config is 3000)
    environment:
      # Inside Docker, your app must bind to 0.0.0.0, not localhost:
      - HOST=0.0.0.0
      # Database configuration
      - IDM_PG_HOST=powercard_db
      - IDM_PG_PORT=5432
      - IDM_PG_DATABASE=powercard_db
      - IDM_PG_USER=bat
      - IDM_PG_PASSWORD=pwd
      # JWT configuration
      - JWT_SECRET=very-secure-jwt-secret
      - COOKIE_HTTP_ONLY=true
      - COOKIE_SECURE=false
      - ACCESS_TOKEN_EXPIRY=5m
      - REFRESH_TOKEN_EXPIRY=15m
      - TEMP_TOKEN_EXPIRY=10m
      - LOGOUT_TOKEN_EXPIRY=-1m
      - JWT_ISSUER=simple-idm
      - JWT_AUDIENCE=simple-idm
      # Email configuration
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
      - EMAIL_USERNAME=noreply@example.com
      - EMAIL_PASSWORD=pwd
      - EMAIL_FROM=noreply@example.com
      # Password complexity
      - PASSWORD_COMPLEXITY_REQUIRE_DIGIT=false
      - PASSWORD_COMPLEXITY_REQUIRE_LOWERCASE=true
      - PASSWORD_COMPLEXITY_REQUIRE_NON_ALPHANUMERIC=false
      - PASSWORD_COMPLEXITY_REQUIRE_UPPERCASE=false
      - PASSWORD_COMPLEXITY_REQUIRED_LENGTH=3
      - PASSWORD_COMPLEXITY_DISALLOW_COMMON_PWDS=false
      - PASSWORD_COMPLEXITY_MAX_REPEATED_CHARS=3
      - PASSWORD_COMPLEXITY_HISTORY_CHECK_COUNT=0
      - PASSWORD_COMPLEXITY_EXPIRATION_DAYS=90
      # Device expiration
      - DEVICE_EXPIRATION_DAYS=2160h  # 90 days in hours (90*24)
      # Base URL
      - BASE_URL=http://localhost:4000
    networks:
      - powercard-net
    depends_on:
      # - db
      - mailpit
    command: ["/app/cmd/login"]  # Use the login binary

  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=idm
  #     - POSTGRES_PASSWORD=pwd
  #     - POSTGRES_DB=idm_db
  #   ports:
  #     - "5432:5432"  # Map to the provided port
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U idm"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # migrate:
  #   build: ./migrations
  #   # depends_on:
  #     # db:
  #     #   condition: service_healthy
  #   environment:
  #     GOOSE_DRIVER: postgres
  #     GOOSE_DBSTRING: postgres://idm:pwd@db:5432/idm_db?sslmode=disable
  #   volumes:
  #     - ./migrations/idm:/migrations/idm
  #   command: /go/bin/goose -dir /migrations/idm up

  seed:
    image: postgres:16
    # depends_on:
    #   migrate:
    #     condition: service_completed_successfully
    volumes:
      - ./migrations/seed.sql:/seed.sql
    entrypoint: ["sh", "-c", "psql -U bat -d powercard_db -h powercard_db -p 5432 -f /seed.sql"]
    networks:
      - powercard-net
    environment:
      PGPASSWORD: pwd

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP server
    environment:
      - MP_MAX_MESSAGES=500
      - MP_DATA_FILE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  mailpit_data:

networks:
  powercard-net:
    external: true